# Generated by Django 5.0.2 on 2024-02-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=100)),
                ('subtask', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=10)),
                ('prio', models.CharField(max_length=1)),
            ],
        ),
    ]
