# Generated by Django 5.0.2 on 2024-02-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtaskitem',
            name='assigned_to',
            field=models.JSONField(default=list),
        ),
    ]
