# Generated by Django 5.0.2 on 2024-02-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_addtaskitem_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtaskitem',
            name='processing_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addtaskitem',
            name='prio',
            field=models.IntegerField(default=0),
        ),
    ]
