# Generated by Django 5.0.2 on 2024-02-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_addtaskitem_processing_status_alter_addtaskitem_prio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('name_abbreviation', models.CharField(max_length=2)),
                ('background_color', models.CharField(max_length=7)),
                ('checked', models.BooleanField(default=False, verbose_name='')),
            ],
        ),
    ]
