# Generated by Django 5.0.2 on 2024-02-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_contactsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtaskitem',
            name='subtask',
            field=models.JSONField(default=list),
        ),
    ]
