# Generated by Django 5.0.2 on 2024-02-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_addtaskitem_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtaskitem',
            name='subtask',
            field=models.CharField(max_length=100),
        ),
    ]
