# Generated by Django 5.0.2 on 2024-02-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_contactsitem_has_account_contactsitem_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsitem',
            name='id_user',
            field=models.IntegerField(default=''),
        ),
    ]
