# Generated by Django 5.0.2 on 2024-02-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_contactsitem_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsitem',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactsitem',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name=''),
        ),
    ]
